/*
Superlink

API for Superlink

API version: v0.4.1
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superlink

import (
	"encoding/json"
)

// checks if the ApiParentDomainPurchaseRequestDomainContactDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiParentDomainPurchaseRequestDomainContactDetails{}

// ApiParentDomainPurchaseRequestDomainContactDetails struct for ApiParentDomainPurchaseRequestDomainContactDetails
type ApiParentDomainPurchaseRequestDomainContactDetails struct {
	Address1 *string `json:"address1,omitempty"`
	Address2 *string `json:"address2,omitempty"`
	City *string `json:"city,omitempty"`
	Country *string `json:"country,omitempty"`
	Email *string `json:"email,omitempty"`
	NameFirst *string `json:"nameFirst,omitempty"`
	NameLast *string `json:"nameLast,omitempty"`
	PhoneCountryCode *string `json:"phoneCountryCode,omitempty"`
	PhoneNumber *string `json:"phoneNumber,omitempty"`
	PostalCode *string `json:"postalCode,omitempty"`
	State *string `json:"state,omitempty"`
}

// NewApiParentDomainPurchaseRequestDomainContactDetails instantiates a new ApiParentDomainPurchaseRequestDomainContactDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiParentDomainPurchaseRequestDomainContactDetails() *ApiParentDomainPurchaseRequestDomainContactDetails {
	this := ApiParentDomainPurchaseRequestDomainContactDetails{}
	return &this
}

// NewApiParentDomainPurchaseRequestDomainContactDetailsWithDefaults instantiates a new ApiParentDomainPurchaseRequestDomainContactDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiParentDomainPurchaseRequestDomainContactDetailsWithDefaults() *ApiParentDomainPurchaseRequestDomainContactDetails {
	this := ApiParentDomainPurchaseRequestDomainContactDetails{}
	return &this
}

// GetAddress1 returns the Address1 field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetAddress1() string {
	if o == nil || IsNil(o.Address1) {
		var ret string
		return ret
	}
	return *o.Address1
}

// GetAddress1Ok returns a tuple with the Address1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetAddress1Ok() (*string, bool) {
	if o == nil || IsNil(o.Address1) {
		return nil, false
	}
	return o.Address1, true
}

// HasAddress1 returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasAddress1() bool {
	if o != nil && !IsNil(o.Address1) {
		return true
	}

	return false
}

// SetAddress1 gets a reference to the given string and assigns it to the Address1 field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetAddress1(v string) {
	o.Address1 = &v
}

// GetAddress2 returns the Address2 field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetAddress2() string {
	if o == nil || IsNil(o.Address2) {
		var ret string
		return ret
	}
	return *o.Address2
}

// GetAddress2Ok returns a tuple with the Address2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetAddress2Ok() (*string, bool) {
	if o == nil || IsNil(o.Address2) {
		return nil, false
	}
	return o.Address2, true
}

// HasAddress2 returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasAddress2() bool {
	if o != nil && !IsNil(o.Address2) {
		return true
	}

	return false
}

// SetAddress2 gets a reference to the given string and assigns it to the Address2 field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetAddress2(v string) {
	o.Address2 = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetCity(v string) {
	o.City = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetCountry(v string) {
	o.Country = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetEmail(v string) {
	o.Email = &v
}

// GetNameFirst returns the NameFirst field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetNameFirst() string {
	if o == nil || IsNil(o.NameFirst) {
		var ret string
		return ret
	}
	return *o.NameFirst
}

// GetNameFirstOk returns a tuple with the NameFirst field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetNameFirstOk() (*string, bool) {
	if o == nil || IsNil(o.NameFirst) {
		return nil, false
	}
	return o.NameFirst, true
}

// HasNameFirst returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasNameFirst() bool {
	if o != nil && !IsNil(o.NameFirst) {
		return true
	}

	return false
}

// SetNameFirst gets a reference to the given string and assigns it to the NameFirst field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetNameFirst(v string) {
	o.NameFirst = &v
}

// GetNameLast returns the NameLast field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetNameLast() string {
	if o == nil || IsNil(o.NameLast) {
		var ret string
		return ret
	}
	return *o.NameLast
}

// GetNameLastOk returns a tuple with the NameLast field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetNameLastOk() (*string, bool) {
	if o == nil || IsNil(o.NameLast) {
		return nil, false
	}
	return o.NameLast, true
}

// HasNameLast returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasNameLast() bool {
	if o != nil && !IsNil(o.NameLast) {
		return true
	}

	return false
}

// SetNameLast gets a reference to the given string and assigns it to the NameLast field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetNameLast(v string) {
	o.NameLast = &v
}

// GetPhoneCountryCode returns the PhoneCountryCode field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPhoneCountryCode() string {
	if o == nil || IsNil(o.PhoneCountryCode) {
		var ret string
		return ret
	}
	return *o.PhoneCountryCode
}

// GetPhoneCountryCodeOk returns a tuple with the PhoneCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPhoneCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneCountryCode) {
		return nil, false
	}
	return o.PhoneCountryCode, true
}

// HasPhoneCountryCode returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasPhoneCountryCode() bool {
	if o != nil && !IsNil(o.PhoneCountryCode) {
		return true
	}

	return false
}

// SetPhoneCountryCode gets a reference to the given string and assigns it to the PhoneCountryCode field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetPhoneCountryCode(v string) {
	o.PhoneCountryCode = &v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPhoneNumber() string {
	if o == nil || IsNil(o.PhoneNumber) {
		var ret string
		return ret
	}
	return *o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPhoneNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneNumber) {
		return nil, false
	}
	return o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasPhoneNumber() bool {
	if o != nil && !IsNil(o.PhoneNumber) {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given string and assigns it to the PhoneNumber field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetPhoneNumber(v string) {
	o.PhoneNumber = &v
}

// GetPostalCode returns the PostalCode field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPostalCode() string {
	if o == nil || IsNil(o.PostalCode) {
		var ret string
		return ret
	}
	return *o.PostalCode
}

// GetPostalCodeOk returns a tuple with the PostalCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetPostalCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PostalCode) {
		return nil, false
	}
	return o.PostalCode, true
}

// HasPostalCode returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasPostalCode() bool {
	if o != nil && !IsNil(o.PostalCode) {
		return true
	}

	return false
}

// SetPostalCode gets a reference to the given string and assigns it to the PostalCode field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetPostalCode(v string) {
	o.PostalCode = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ApiParentDomainPurchaseRequestDomainContactDetails) SetState(v string) {
	o.State = &v
}

func (o ApiParentDomainPurchaseRequestDomainContactDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiParentDomainPurchaseRequestDomainContactDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address1) {
		toSerialize["address1"] = o.Address1
	}
	if !IsNil(o.Address2) {
		toSerialize["address2"] = o.Address2
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Country) {
		toSerialize["country"] = o.Country
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.NameFirst) {
		toSerialize["nameFirst"] = o.NameFirst
	}
	if !IsNil(o.NameLast) {
		toSerialize["nameLast"] = o.NameLast
	}
	if !IsNil(o.PhoneCountryCode) {
		toSerialize["phoneCountryCode"] = o.PhoneCountryCode
	}
	if !IsNil(o.PhoneNumber) {
		toSerialize["phoneNumber"] = o.PhoneNumber
	}
	if !IsNil(o.PostalCode) {
		toSerialize["postalCode"] = o.PostalCode
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	return toSerialize, nil
}

type NullableApiParentDomainPurchaseRequestDomainContactDetails struct {
	value *ApiParentDomainPurchaseRequestDomainContactDetails
	isSet bool
}

func (v NullableApiParentDomainPurchaseRequestDomainContactDetails) Get() *ApiParentDomainPurchaseRequestDomainContactDetails {
	return v.value
}

func (v *NullableApiParentDomainPurchaseRequestDomainContactDetails) Set(val *ApiParentDomainPurchaseRequestDomainContactDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableApiParentDomainPurchaseRequestDomainContactDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableApiParentDomainPurchaseRequestDomainContactDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiParentDomainPurchaseRequestDomainContactDetails(val *ApiParentDomainPurchaseRequestDomainContactDetails) *NullableApiParentDomainPurchaseRequestDomainContactDetails {
	return &NullableApiParentDomainPurchaseRequestDomainContactDetails{value: val, isSet: true}
}

func (v NullableApiParentDomainPurchaseRequestDomainContactDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiParentDomainPurchaseRequestDomainContactDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


