/*
Superlink

API for Superlink

API version: v0.5.0
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superlink

import (
	"encoding/json"
)

// checks if the ApiMarketCryptoEstimationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMarketCryptoEstimationResponse{}

// ApiMarketCryptoEstimationResponse struct for ApiMarketCryptoEstimationResponse
type ApiMarketCryptoEstimationResponse struct {
	Estimations []ApiMarketCryptoEstimation `json:"estimations,omitempty"`
	FiatCurrency *string `json:"fiatCurrency,omitempty"`
	Region *string `json:"region,omitempty"`
}

// NewApiMarketCryptoEstimationResponse instantiates a new ApiMarketCryptoEstimationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMarketCryptoEstimationResponse() *ApiMarketCryptoEstimationResponse {
	this := ApiMarketCryptoEstimationResponse{}
	return &this
}

// NewApiMarketCryptoEstimationResponseWithDefaults instantiates a new ApiMarketCryptoEstimationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMarketCryptoEstimationResponseWithDefaults() *ApiMarketCryptoEstimationResponse {
	this := ApiMarketCryptoEstimationResponse{}
	return &this
}

// GetEstimations returns the Estimations field value if set, zero value otherwise.
func (o *ApiMarketCryptoEstimationResponse) GetEstimations() []ApiMarketCryptoEstimation {
	if o == nil || IsNil(o.Estimations) {
		var ret []ApiMarketCryptoEstimation
		return ret
	}
	return o.Estimations
}

// GetEstimationsOk returns a tuple with the Estimations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketCryptoEstimationResponse) GetEstimationsOk() ([]ApiMarketCryptoEstimation, bool) {
	if o == nil || IsNil(o.Estimations) {
		return nil, false
	}
	return o.Estimations, true
}

// HasEstimations returns a boolean if a field has been set.
func (o *ApiMarketCryptoEstimationResponse) HasEstimations() bool {
	if o != nil && !IsNil(o.Estimations) {
		return true
	}

	return false
}

// SetEstimations gets a reference to the given []ApiMarketCryptoEstimation and assigns it to the Estimations field.
func (o *ApiMarketCryptoEstimationResponse) SetEstimations(v []ApiMarketCryptoEstimation) {
	o.Estimations = v
}

// GetFiatCurrency returns the FiatCurrency field value if set, zero value otherwise.
func (o *ApiMarketCryptoEstimationResponse) GetFiatCurrency() string {
	if o == nil || IsNil(o.FiatCurrency) {
		var ret string
		return ret
	}
	return *o.FiatCurrency
}

// GetFiatCurrencyOk returns a tuple with the FiatCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketCryptoEstimationResponse) GetFiatCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.FiatCurrency) {
		return nil, false
	}
	return o.FiatCurrency, true
}

// HasFiatCurrency returns a boolean if a field has been set.
func (o *ApiMarketCryptoEstimationResponse) HasFiatCurrency() bool {
	if o != nil && !IsNil(o.FiatCurrency) {
		return true
	}

	return false
}

// SetFiatCurrency gets a reference to the given string and assigns it to the FiatCurrency field.
func (o *ApiMarketCryptoEstimationResponse) SetFiatCurrency(v string) {
	o.FiatCurrency = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *ApiMarketCryptoEstimationResponse) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketCryptoEstimationResponse) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *ApiMarketCryptoEstimationResponse) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *ApiMarketCryptoEstimationResponse) SetRegion(v string) {
	o.Region = &v
}

func (o ApiMarketCryptoEstimationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMarketCryptoEstimationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Estimations) {
		toSerialize["estimations"] = o.Estimations
	}
	if !IsNil(o.FiatCurrency) {
		toSerialize["fiatCurrency"] = o.FiatCurrency
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableApiMarketCryptoEstimationResponse struct {
	value *ApiMarketCryptoEstimationResponse
	isSet bool
}

func (v NullableApiMarketCryptoEstimationResponse) Get() *ApiMarketCryptoEstimationResponse {
	return v.value
}

func (v *NullableApiMarketCryptoEstimationResponse) Set(val *ApiMarketCryptoEstimationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMarketCryptoEstimationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMarketCryptoEstimationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMarketCryptoEstimationResponse(val *ApiMarketCryptoEstimationResponse) *NullableApiMarketCryptoEstimationResponse {
	return &NullableApiMarketCryptoEstimationResponse{value: val, isSet: true}
}

func (v NullableApiMarketCryptoEstimationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMarketCryptoEstimationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


