/*
Superlink

API for Superlink

API version: 1.0
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package SuperlinkAPI

import (
	"encoding/json"
)

// checks if the ApiResponseInternalServerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiResponseInternalServerError{}

// ApiResponseInternalServerError struct for ApiResponseInternalServerError
type ApiResponseInternalServerError struct {
	Message *string `json:"message,omitempty"`
}

// NewApiResponseInternalServerError instantiates a new ApiResponseInternalServerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiResponseInternalServerError() *ApiResponseInternalServerError {
	this := ApiResponseInternalServerError{}
	return &this
}

// NewApiResponseInternalServerErrorWithDefaults instantiates a new ApiResponseInternalServerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiResponseInternalServerErrorWithDefaults() *ApiResponseInternalServerError {
	this := ApiResponseInternalServerError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApiResponseInternalServerError) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiResponseInternalServerError) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApiResponseInternalServerError) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApiResponseInternalServerError) SetMessage(v string) {
	o.Message = &v
}

func (o ApiResponseInternalServerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiResponseInternalServerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableApiResponseInternalServerError struct {
	value *ApiResponseInternalServerError
	isSet bool
}

func (v NullableApiResponseInternalServerError) Get() *ApiResponseInternalServerError {
	return v.value
}

func (v *NullableApiResponseInternalServerError) Set(val *ApiResponseInternalServerError) {
	v.value = val
	v.isSet = true
}

func (v NullableApiResponseInternalServerError) IsSet() bool {
	return v.isSet
}

func (v *NullableApiResponseInternalServerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiResponseInternalServerError(val *ApiResponseInternalServerError) *NullableApiResponseInternalServerError {
	return &NullableApiResponseInternalServerError{value: val, isSet: true}
}

func (v NullableApiResponseInternalServerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiResponseInternalServerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


