/*
Superlink

API for Superlink

API version: v0.4.2
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superlink

import (
	"encoding/json"
)

// checks if the ApiSubDomainResolveResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSubDomainResolveResponse{}

// ApiSubDomainResolveResponse struct for ApiSubDomainResolveResponse
type ApiSubDomainResolveResponse struct {
	Domain *string `json:"domain,omitempty"`
	NameData *ApiSubDomainNameData `json:"nameData,omitempty"`
}

// NewApiSubDomainResolveResponse instantiates a new ApiSubDomainResolveResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSubDomainResolveResponse() *ApiSubDomainResolveResponse {
	this := ApiSubDomainResolveResponse{}
	return &this
}

// NewApiSubDomainResolveResponseWithDefaults instantiates a new ApiSubDomainResolveResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSubDomainResolveResponseWithDefaults() *ApiSubDomainResolveResponse {
	this := ApiSubDomainResolveResponse{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ApiSubDomainResolveResponse) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubDomainResolveResponse) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ApiSubDomainResolveResponse) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ApiSubDomainResolveResponse) SetDomain(v string) {
	o.Domain = &v
}

// GetNameData returns the NameData field value if set, zero value otherwise.
func (o *ApiSubDomainResolveResponse) GetNameData() ApiSubDomainNameData {
	if o == nil || IsNil(o.NameData) {
		var ret ApiSubDomainNameData
		return ret
	}
	return *o.NameData
}

// GetNameDataOk returns a tuple with the NameData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSubDomainResolveResponse) GetNameDataOk() (*ApiSubDomainNameData, bool) {
	if o == nil || IsNil(o.NameData) {
		return nil, false
	}
	return o.NameData, true
}

// HasNameData returns a boolean if a field has been set.
func (o *ApiSubDomainResolveResponse) HasNameData() bool {
	if o != nil && !IsNil(o.NameData) {
		return true
	}

	return false
}

// SetNameData gets a reference to the given ApiSubDomainNameData and assigns it to the NameData field.
func (o *ApiSubDomainResolveResponse) SetNameData(v ApiSubDomainNameData) {
	o.NameData = &v
}

func (o ApiSubDomainResolveResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSubDomainResolveResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.NameData) {
		toSerialize["nameData"] = o.NameData
	}
	return toSerialize, nil
}

type NullableApiSubDomainResolveResponse struct {
	value *ApiSubDomainResolveResponse
	isSet bool
}

func (v NullableApiSubDomainResolveResponse) Get() *ApiSubDomainResolveResponse {
	return v.value
}

func (v *NullableApiSubDomainResolveResponse) Set(val *ApiSubDomainResolveResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSubDomainResolveResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSubDomainResolveResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSubDomainResolveResponse(val *ApiSubDomainResolveResponse) *NullableApiSubDomainResolveResponse {
	return &NullableApiSubDomainResolveResponse{value: val, isSet: true}
}

func (v NullableApiSubDomainResolveResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSubDomainResolveResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


