/*
Superlink

API for Superlink

API version: v0.5.0
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superlink

import (
	"encoding/json"
)

// checks if the ApiHNSCreateDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiHNSCreateDomainRequest{}

// ApiHNSCreateDomainRequest struct for ApiHNSCreateDomainRequest
type ApiHNSCreateDomainRequest struct {
	Addresses *map[string]string `json:"addresses,omitempty"`
	Domain *string `json:"domain,omitempty"`
	OwnerAddress *string `json:"ownerAddress,omitempty"`
}

// NewApiHNSCreateDomainRequest instantiates a new ApiHNSCreateDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiHNSCreateDomainRequest() *ApiHNSCreateDomainRequest {
	this := ApiHNSCreateDomainRequest{}
	return &this
}

// NewApiHNSCreateDomainRequestWithDefaults instantiates a new ApiHNSCreateDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiHNSCreateDomainRequestWithDefaults() *ApiHNSCreateDomainRequest {
	this := ApiHNSCreateDomainRequest{}
	return &this
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *ApiHNSCreateDomainRequest) GetAddresses() map[string]string {
	if o == nil || IsNil(o.Addresses) {
		var ret map[string]string
		return ret
	}
	return *o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiHNSCreateDomainRequest) GetAddressesOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *ApiHNSCreateDomainRequest) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given map[string]string and assigns it to the Addresses field.
func (o *ApiHNSCreateDomainRequest) SetAddresses(v map[string]string) {
	o.Addresses = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ApiHNSCreateDomainRequest) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiHNSCreateDomainRequest) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ApiHNSCreateDomainRequest) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ApiHNSCreateDomainRequest) SetDomain(v string) {
	o.Domain = &v
}

// GetOwnerAddress returns the OwnerAddress field value if set, zero value otherwise.
func (o *ApiHNSCreateDomainRequest) GetOwnerAddress() string {
	if o == nil || IsNil(o.OwnerAddress) {
		var ret string
		return ret
	}
	return *o.OwnerAddress
}

// GetOwnerAddressOk returns a tuple with the OwnerAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiHNSCreateDomainRequest) GetOwnerAddressOk() (*string, bool) {
	if o == nil || IsNil(o.OwnerAddress) {
		return nil, false
	}
	return o.OwnerAddress, true
}

// HasOwnerAddress returns a boolean if a field has been set.
func (o *ApiHNSCreateDomainRequest) HasOwnerAddress() bool {
	if o != nil && !IsNil(o.OwnerAddress) {
		return true
	}

	return false
}

// SetOwnerAddress gets a reference to the given string and assigns it to the OwnerAddress field.
func (o *ApiHNSCreateDomainRequest) SetOwnerAddress(v string) {
	o.OwnerAddress = &v
}

func (o ApiHNSCreateDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiHNSCreateDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.OwnerAddress) {
		toSerialize["ownerAddress"] = o.OwnerAddress
	}
	return toSerialize, nil
}

type NullableApiHNSCreateDomainRequest struct {
	value *ApiHNSCreateDomainRequest
	isSet bool
}

func (v NullableApiHNSCreateDomainRequest) Get() *ApiHNSCreateDomainRequest {
	return v.value
}

func (v *NullableApiHNSCreateDomainRequest) Set(val *ApiHNSCreateDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiHNSCreateDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiHNSCreateDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiHNSCreateDomainRequest(val *ApiHNSCreateDomainRequest) *NullableApiHNSCreateDomainRequest {
	return &NullableApiHNSCreateDomainRequest{value: val, isSet: true}
}

func (v NullableApiHNSCreateDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiHNSCreateDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


