/*
Superlink

API for Superlink

API version: v0.5.0
Contact: support@superlink.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superlink

import (
	"encoding/json"
)

// checks if the ApiMarketSuggestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMarketSuggestRequest{}

// ApiMarketSuggestRequest struct for ApiMarketSuggestRequest
type ApiMarketSuggestRequest struct {
	Addrs []ApiAddressRecord `json:"addrs,omitempty"`
	Query *string `json:"query,omitempty"`
}

// NewApiMarketSuggestRequest instantiates a new ApiMarketSuggestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMarketSuggestRequest() *ApiMarketSuggestRequest {
	this := ApiMarketSuggestRequest{}
	return &this
}

// NewApiMarketSuggestRequestWithDefaults instantiates a new ApiMarketSuggestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMarketSuggestRequestWithDefaults() *ApiMarketSuggestRequest {
	this := ApiMarketSuggestRequest{}
	return &this
}

// GetAddrs returns the Addrs field value if set, zero value otherwise.
func (o *ApiMarketSuggestRequest) GetAddrs() []ApiAddressRecord {
	if o == nil || IsNil(o.Addrs) {
		var ret []ApiAddressRecord
		return ret
	}
	return o.Addrs
}

// GetAddrsOk returns a tuple with the Addrs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketSuggestRequest) GetAddrsOk() ([]ApiAddressRecord, bool) {
	if o == nil || IsNil(o.Addrs) {
		return nil, false
	}
	return o.Addrs, true
}

// HasAddrs returns a boolean if a field has been set.
func (o *ApiMarketSuggestRequest) HasAddrs() bool {
	if o != nil && !IsNil(o.Addrs) {
		return true
	}

	return false
}

// SetAddrs gets a reference to the given []ApiAddressRecord and assigns it to the Addrs field.
func (o *ApiMarketSuggestRequest) SetAddrs(v []ApiAddressRecord) {
	o.Addrs = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *ApiMarketSuggestRequest) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMarketSuggestRequest) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *ApiMarketSuggestRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *ApiMarketSuggestRequest) SetQuery(v string) {
	o.Query = &v
}

func (o ApiMarketSuggestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMarketSuggestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Addrs) {
		toSerialize["addrs"] = o.Addrs
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	return toSerialize, nil
}

type NullableApiMarketSuggestRequest struct {
	value *ApiMarketSuggestRequest
	isSet bool
}

func (v NullableApiMarketSuggestRequest) Get() *ApiMarketSuggestRequest {
	return v.value
}

func (v *NullableApiMarketSuggestRequest) Set(val *ApiMarketSuggestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMarketSuggestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMarketSuggestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMarketSuggestRequest(val *ApiMarketSuggestRequest) *NullableApiMarketSuggestRequest {
	return &NullableApiMarketSuggestRequest{value: val, isSet: true}
}

func (v NullableApiMarketSuggestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMarketSuggestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


