name: Generate Client

on:
  workflow_dispatch:
  repository_dispatch:
    types: [generate_code]

jobs:
  generate-go-client:
    runs-on: ubuntu-latest
    name: Generate a Go client
    env: 
      CI_COMMIT_MESSAGE: automated commit
      CI_COMMIT_AUTHOR: Superlink Bot
      CI_COMMIT_EMAIL: henry+superlinkbot@superlink.me
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
        
      - name: Set version
        run: |
          cat ./generator-config.yml >> ./generator-config-edit.yml
          echo "packageVersion: \"${{ github.event.client_payload.tag }}\"" >> ./generator-config-edit.yml
          
      - name: Generate Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: go
          openapi-url: https://api.superlink.me/v1/docs/doc.json
          config-file: ./generator-config-edit.yml

      - name: Clean
        run: |
          rsync -a ./go-client/ ./
          rm -Rf ./go-client
          rm ./generator-config-edit.yml

      - name: Push and Tag
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            echo "changes found, commiting"
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
            git add .
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.client_payload.tag }}
          name: ${{ github.event.client_payload.release_name }}
          body: ${{ github.event.client_payload.release_body }}
          draft: ${{ github.event.client_payload.release_draft }}
          prerelease:  ${{ github.event.client_payload.release_prerelease }}
      - name: Send failure message to Slack
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":red_circle: Go client ${{ github.event.client_payload.tag }} generation failed!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send success message to Slack
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":large_green_circle: Go client ${{ github.event.client_payload.tag }} generation succeeded!"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
