name: Go Proxy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Renew documentation
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull new module version'
        uses: andrewslotin/go-proxy-pull-action@master